export default interface Order {
  order_id: number;
  email: string;
  phone: string;
  cpf?: string;
  cnpj?: string;
  invoice_name: string;
  invoice_lastname: string;
  invoice_cep: string;
  invoice_street: string;
  invoice_number: string;
  invoice_complement: string;
  invoice_district: string;
  invoice_city: string;
  invoice_state: string;
  shipping_category: string;
  shipping_cost: string;
  shipping_name: string;
  shipping_lastname: string;
  shipping_cep: string;
  shipping_street: string;
  shipping_number: string;
  shipping_complement: string;
  shipping_district: string;
  shipping_city: string;
  shipping_state: string;
};
